[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "playwright_p"
version = "0.1.0"
description = "Playwright automation framework"
requires-python = ">=3.10"

dependencies = [
    "pytest",
    "playwright",
    "pytest-playwright",
    "allure-pytest",
    "pytest-xdist",
    "pytest-rerunfailures",
    "allure-python-commons",
    "python-dotenv",
    "ruff",
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
python_functions = "test_*"

[tool.ruff]
line-length = 200

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.mypy]
python_version = "3.12"
mypy_path = "src"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    "tests.*",
]
disallow_untyped_defs = false
disallow_untyped_calls = false