[pytest]
addopts = --alluredir=reports/allure-results
          --reruns 1 --reruns-delay 1
          --screenshot=off
          --output=reports/test-results
          --tracing=retain-on-failure
          --video=retain-on-failure
          --allure-screenshots=off
testpaths = src/tests
python_files = test_*.py
markers =
    playwright: mark Playwright tests
