[pytest]
addopts = --alluredir=reports/allure-results
          --reruns 1 --reruns-delay 1
          --screenshot=off
          --tracing=retain-on-failure --video=retain-on-failure
testpaths = src/tests
python_files = test_*.py
markers =
    playwright: mark Playwright tests
