[pytest]
addopts = --alluredir=reports/allure-results -n auto
          --reruns 1 --reruns-delay 1
          --screenshot=on
          --tracing=retain-on-failure --video=retain-on-failure
testpaths = tests
python_files = test_*.py
markers =
    playwright: mark Playwright tests
